name: "Test"

on:
  pull_request:
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive

concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-myapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -e .
          venv/bin/pip install -r requirements.txt
      - name: Run tests
        run: |
          venv/bin/pytest \
            --cov --cov-report=lcov --cov-report=html
      - uses: actions/upload-artifact@v3
        with:
          name: myapp-coverage-data
          path: |
            test_results/**
            htmlcov/**
      - name: Send coverage data to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: lcov-myapp
          parallel: true

  does-nothing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Does nothing"

  generate-coverage-report:
    runs-on: ubuntu-latest
    needs: [test-myapp, does-nothing]
    steps:
      - name: Coveralls
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
